---
- name: biuld fusebox
  hosts: build-srv
  become: yes

  tasks:
  - name: Ensure default-jdk package is present
    apt:
      name: default-jdk
      state: present

  - name: Ensure maven package is present
    apt:
      name: maven
      state: present

  - name: Ensure git package is present
    apt:
      name: git
      state: present

  - name: Clone a repo 
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /tmp/boxfuse

  - name: This command will change the working directory to somedir/
    shell:
      chdir: /tmp/boxfuse/boxfuse-sample-java-war-hello
      cmd: mvn package
      
  - name: fetch WAR
    fetch:
      src: /tmp/boxfuse/boxfuse-sample-java-war-hello/target/hello-1.0.war
      dest: ./hello-1.0.war
      flat: true

- name: run fusebox
  hosts: prod-srv
  become: yes

  tasks:
  - name: Ensure default-jdk package is present
    apt:
      name: default-jdk
      state: present

  - name: Ensure tomcat9 package is present
    apt:
      name: tomcat9
      state: present

  - name: Ensure tomcat9 service is started
    service:
      name: tomcat9
      state: started
  - name: Copy WAR
    copy:
      src: ./hello-1.0.war
      dest: /var/lib/tomcat9/webapps/hello-1.0.war


