---
- name: biuld fusebox
  hosts: build-srvs
  become: yes

  tasks:
  - name: Ensure default-jdk package is present
    apt:
      name: default-jdk
      state: present

  - name: Ensure maven package is present
    apt:
      name: maven
      state: present

  - name: Ensure git package is present
    apt:
      name: git
      state: present

  - name: Clone a repo 
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /tmp/boxfuse

  - name: Change the working directory and run maven package
    shell:
      chdir: /tmp/boxfuse
      cmd: mvn package
      
  - name: synchronize WAR
    synchronize:
      src: /tmp/boxfuse/target/hello-1.0.war
      dest: /var/lib/tomcat9/webapps/hello-1.0.war
    delegate_to: prod-srv

- name: run fusebox
  hosts: prod-srvs
  become: yes

  tasks:
  - name: Ensure default-jdk package is present
    apt:
      name: default-jdk
      state: present

  - name: Ensure tomcat9 package is present
    apt:
      name: tomcat9
      state: present

  - name: Ensure tomcat9 service is started
    service:
      name: tomcat9
      state: started


